#!/bin/bash
# This is an all-in-one script to run the evaluation and equivalence check for a given design.
# Can be run wherever you want, as long as TOP_PROJ_DIR is set correctly.
umask 000
export TOP_PROJ_DIR="/workspace/ISPD26_VDALAB"
export PROJ_DIR="${TOP_PROJ_DIR}/scripts"
OR_EXE="/OpenROAD/build/bin/openroad"
# export DESIGN_NAME="aes_cipher_top"
# export FOLDER_NAME="TCP_250_UTIL_0.40"

# DESIGN_NAME is passed as first argument
export DESIGN_NAME="$1"

# Default values
POST_OPT=1
EQ_CHECK=1

# Parse positional arguments for POST_OPT= or EQ_CHECK=
# logic: 
# 1. Loop through the second and third arguments (if they exist)
# 2. If an argument starts with "POST_OPT=", extract the value and set POST_OPT
# 3. If an argument starts with "EQ_CHECK=", extract the value and set EQ_CHECK
for arg in "$2" "$3"; do
    if [[ $arg == POST_OPT=* ]]; then
        POST_OPT="${arg#POST_OPT=}"
    elif [[ $arg == EQ_CHECK=* ]]; then
        EQ_CHECK="${arg#EQ_CHECK=}"
    fi
done

export POST_OPT
export EQ_CHECK

# FOLDER_NAME is the one and only subdir of DESIGN_NAME
export FOLDER_NAME=$(find ${TOP_PROJ_DIR}/Benchmarks/${DESIGN_NAME} -mindepth 1 -maxdepth 1 -type d | xargs -n 1 basename)

# Extract the substring before "_v2" in DESIGN_NAME to get the top module name
export TOP_MODULE="${DESIGN_NAME%%_v2*}"
echo "Design Name: ${DESIGN_NAME}"
echo "Folder Name: ${FOLDER_NAME}"
echo "Top Module: ${TOP_MODULE}"

# LOG_DIR/${DESIGN_NAME}
# | (Below are generated by eval programs)
# |-- evaluation.log
# |-- metrics.csv
# |-- congestion_report.rpt
# | (Below are generated by equiv check programs)
# |-- equiv_cells.log
# |-- node.csv, nets.csv
# | (Generated by ${TOP_PROJ_DIR}/equiv_check/netlist_equiv_check.py)
# |-- eq_check.log
export LOG_DIR="${TOP_PROJ_DIR}/log_file/${DESIGN_NAME}"
export OUTPUT_DIR="${TOP_PROJ_DIR}/output_file"

# mkdir ${FOLDER_NAME} -p
mkdir ${LOG_DIR} -p

# export EVAL_LOG_FILE="$(TOP_PROJ_DIR)/evaluation.log"
export EVAL_LOG_FILE="${LOG_DIR}/evaluation.log"
# export METRICS_CSV="${FOLDER_NAME}/metrics.csv"
export METRICS_CSV="${LOG_DIR}/metrics.csv"
# export CONGESTION_REPORT="${FOLDER_NAME}/congestion_report.rpt"   
export CONGESTION_REPORT="${LOG_DIR}/congestion_report.rpt"

# set the absolute dir of lib_setup_file and design_setup_file 
#  this is to ensure that the evaluation.tcl can be run from any working dir, and the equiv check can also be run from any working dir
export LIB_SETUP="${PROJ_DIR}/${TOP_MODULE}/lib_setup.tcl"
export DESIGN_SETUP="${PROJ_DIR}/smart_eval/design_setup.tcl"
export OR_UTILS="${PROJ_DIR}/smart_eval/or_utils.tcl"

echo "Design Name: ${DESIGN_NAME}"
echo "Running evaluation.tcl..."
$OR_EXE -exit ${PROJ_DIR}/evaluation.tcl | tee ${EVAL_LOG_FILE}

# Equiv check steps, skipped if EQ_CHECK is false or if POST_OPT is false
if [ "$EQ_CHECK" = "false" ] || [ "$POST_OPT" = "false" ]; then
    echo "Skipping equivalence check as EQ_CHECK is set to $EQ_CHECK or POST_OPT is set to $POST_OPT"
    exit 0
fi

# output metrics to csv
echo "Extracting metrics to CSV..."
echo "eval_log path: ${EVAL_LOG_FILE}"
python3 ${PROJ_DIR}/parse_log.py ${EVAL_LOG_FILE} --csv ${METRICS_CSV}

EQ_LOG_FILE="${LOG_DIR}/equiv_cells.log"
echo "Running run_equiv_check.tcl..."
$OR_EXE -exit ${PROJ_DIR}/run_equiv_check.tcl 2>&1 | tee $EQ_LOG_FILE

# run netlist_equiv_check.py
echo "Running netlist_equiv_check.py..."

# record the directory I am at right now
CURRENT_DIR=$(pwd)
cd ${TOP_PROJ_DIR}/equiv_check
python3 ${TOP_PROJ_DIR}/equiv_check/netlist_equiv_check.py \
    --pre_opt "${TOP_PROJ_DIR}/Benchmarks/${DESIGN_NAME}/${FOLDER_NAME}" \
    --post "${LOG_DIR}" \
    2>&1 | tee "${LOG_DIR}/eq_check.log"
# go back 
cd ${CURRENT_DIR}

echo "Done!"

